### ISSUE TITLE
fugashi support

### ISSUE THREAD

**Issue by KoichiYasuoka** [taishi-i/toiro#1]
I often use [fugashi](https://pypi.org/project/fugashi/) instead of mecab-python3, but I'm vague which one is better to use for Japanese dependency-parsing with my [deplacy](https://github.com/KoichiYasuoka/deplacy/blob/master/doc/ja.md). Do you have a plan to include fugashi (and other tokenizers in Stanza, NLP-Cube, spacy-udpipe, etc.) for your `toiro`?

**Comment by taishi-i** [comment]
Hi @KoichiYasuoka ,
I am planning to add the following list of tokenizers to `toiro` that includes `fugashi`. It is scheduled for the beginning of September.
- [JUMAN](http://nlp.ist.i.kyoto-u.ac.jp/?JUMAN)
- [tinysegmenter](https://pypi.org/project/tinysegmenter/)
- [Rakuten MA Python](https://github.com/ikegami-yukino/rakutenma-python)
- [fugashi](https://github.com/polm/fugashi)
- [Stanza](https://github.com/stanfordnlp/stanza)

**Comment by KoichiYasuoka** [comment]
Thank you @taishi-i  for supporting `fugashi`. Now I close this issue.
